## Updated 3.4.23

In [1]:
import numpy as np

from common.arguments import parse_args
import torch

import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import os
import sys
import errno
import pandas as pd
from common.camera import *
from common.model import *
from common.loss import *
from common.generators import ChunkedGenerator, UnchunkedGenerator
from time import time
from common.utils import deterministic_random

In [1]:
import cv2

ModuleNotFoundError: No module named 'cv2'

In [5]:
csv_path = r'testExportV2.csv'
world_cords = pd.read_csv( csv_path)
world_cords= world_cords.iloc[:,2:]

In [22]:
Mworld2cam = np.array([[-9.99747803e-01, -2.23832807e-02,  1.82172852e-03,  -6.43337832e-01],
       [ 4.94293438e-03, -1.40192706e-01,  9.90111899e-01, -1.08866625e+02],
       [-2.19065595e-02,  9.89871201e-01,  1.40267989e-01,   -1.22771195e+03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,   1.00000000e+00]])

In [23]:
# Relbow #
Xcor = 23.31
Ycor = -3.61
Zcor = 135.6

pworld= np.array([Xcor, Ycor , Zcor,1])
pworld

array([ 23.31,  -3.61, 135.6 ,   1.  ])

In [30]:
pcam = np.dot(Mworld2cam,pworld)
np.round(pcam,3)

array([-2.362000e+01,  2.601400e+01, -1.212776e+03,  1.000000e+00])

In [31]:
from scipy.spatial.transform import Rotation as R
r = R.from_matrix(Mcam2world[:3,:3])
Rot = r.as_quat()
Rot = np.append(Rot[3],Rot[:3])
Rot

array([-0.0090482 , -0.00665045,  0.65560794,  0.75501796])

In [32]:
t  = Mcam2world[:,-1][:-1]
t

array([ -27., 1200.,  280.])

In [33]:
pred = pworld[:-1].reshape(1,1,3)
pcam_videopose = world_to_camera(pred, Rot, t)
pcam_videopose

array([[[  -23.6196291 ,    26.01386341, -1212.77569246]]])